/***********************************************************************/
/* This file contains unpublished documentation and software           */
/* proprietary to Cortina Systems Incorporated. Any use or disclosure, */
/* in whole or in part, of the information in this file without a      */
/* written consent of an officer of Cortina Systems Incorporated is    */
/* strictly prohibited.                                                */
/* Copyright (c) 2002 by Cortina Systems Incorporated.                 */
/***********************************************************************/
/*
 * arn5_error.h
 *
 * Error codes for various error callout's from the driver.
 *
 */
#ifndef __ARN5_ERROR_H__
#define __ARN5_ERROR_H__

#include "cs_types.h"

#define EARN5_ERROR_CODE_BASE    ( 0x00050000 )

/* NOTE: Do not change these values! */
#define EARN5_MAX_ERROR_CODES    ( 1000 )
#define EARN5_MAX_DRVR_ERROR_CODES (100)
#define EARN5_MAX_DEV_ERROR_CODES  (200)
#define EARN5_MAX_PORT_ERROR_CODES (700)

typedef enum {
  EARN5_ERROR_CODE_START = EARN5_ERROR_CODE_BASE,

  /* Driver related error code enums start here */
  EARN5_DRVR_CODE_BASE   = EARN5_ERROR_CODE_BASE,
  EARN5_DRVR_ALRDY_LOADED,
  EARN5_DRVR_NOT_LOADED,
  EARN5_DRVR_INCORRECT_ENDIANESS,
  EARN5_ALRDY_OUT_FILE_OPENED,
  EARN5_OUT_FILE_OPEN_ERROR,
  EARN5_NO_OUT_FILE_OPENED,

  /* Device(dev_id) related error code enums start here */
  EARN5_DEV_CODE_BASE= (EARN5_DRVR_CODE_BASE + EARN5_MAX_DRVR_ERROR_CODES),
  EARN5_DEV_ID_OUT_OF_RANGE,
  EARN5_DEV_NOT_REGD,
  EARN5_DEV_NOT_INITED,
  EARN5_CHIP_JTAG_ID_MISMATCH,
  EARN5_DEV_INVALID_HRESET_SEL,
  EARN5_BIST_NOT_DONE,
  EARN5_MBIST_BAD_STATUS,
  EARN5_SBIST_BAD_STATUS,
  EARN5_DEV_INVALID_MODE,
  EARN5_DEV_SEM_INIT_FAILED,
  EARN5_DEV_SEM_TAKE_FAILED,
  EARN5_DEV_CFG_NULL,
  EARN5_DEV_SUMM_NULL,
  EARN5_DEV_INVALID_USER_ARG,
  EARN5_DEV_MALLOC_FAILED,
  EARN5_DEV_NULL_PTR,
  EARN5_DEV_TBL_NULL,
  EARN5_DEV_TBL_START_INVALID,
  EARN5_DEV_TBL_NUM_INVALID,
  EARN5_DEV_RANGE_ERR,
  EARN5_DEV_INVALID_SIZE,
  EARN5_DEV_CFG_VALIDITY_ERR,
  EARN5_DEV_INIT_FAILED,
  EARN5_DEV_CAPACITY_EXCEEDED,
  EARN5_DEV_SPI_CHAN_MAP_FAILED,

  /* Port(port_id) related error code enums start here */
  EARN5_PORT_CODE_BASE= (EARN5_DEV_CODE_BASE + EARN5_MAX_DEV_ERROR_CODES),
  EARN5_PORT_ID_OUT_OF_RANGE,
  EARN5_PORT_NOT_OPEN,
  EARN5_PORT_MALLOC_FAILED,
  EARN5_PORT_SEM_INIT_FAILED,
  EARN5_PORT_SEM_TAKE_FAILED,
  EARN5_PORT_CFG_NULL,
  EARN5_PORT_SUMM_NULL,
  EARN5_PORT_DEBUG_MODE_INVALID,
  EARN5_PORT_CFG_VALIDITY_ERR,
  EARN5_PORT_LOCK_NULL,
  EARN5_PORT_INVALID_OP,
  EARN5_PORT_INVALID_DIR,
  EARN5_PORT_NULL_PTR,
  EARN5_PORT_TBL_NULL,
  EARN5_PORT_TBL_START_INVALID,
  EARN5_PORT_TBL_NUM_INVALID,
  EARN5_PORT_INVALID_MOD_ID,
  EARN5_PORT_MIN_GT_MAX,
  EARN5_PORT_INVALID_REF_CLK,
  EARN5_PORT_RANGE_ERR,
  EARN5_INVALID_HRESET_SEL,
  EARN5_RESET_TIMEOUT,
  EARN5_PORT_INVALID_USER_ARG,
  EARN5_PORT_INVALID_SIZE,

  /* LIF related ERRORS    */
  EARN5_LIF_INVALID_IF,
  EARN5_LIF_INVALID_IN_ETH_MODE,
  EARN5_LIF_INVALID_IN_SONET_MODE,
  EARN5_LIF_INVALID_LPTIME_MODE,
  EARN5_LIF_INVALID_DIGITAL_LB,
  EARN5_LIF_INVALID_ANALOG_LB,
  EARN5_LIF_INVALID_REF_CLK,
  EARN5_LIF_INVALID_ERROR_OP,

  /* FRAMER RELATED ERRORS */
  EARN5_INVALID_IN_FRAMER_MODE,
  EARN5_INVALID_IN_ETH_MODE,
  EARN5_INVALID_OVRHD,
  EARN5_INVALID_FR_DOMAIN,
  EARN5_INVALID_SPE_BW,
  EARN5_INVALID_RX_BURST_LEN,
  EARN5_INVALID_TOH_BYTE,
  EARN5_INVALID_OVRHD_SRC,
  EARN5_OVRHD_SRC_NOT_VALID,
  EARN5_FR_NULL_TRACE_MSG,

  /* ETH related errors */
  EARN5_ETH_RESTART_TIMEOUT,

  /* PPRBS related ERRORS     */
  EARN5_PPRBS_INVALID_CHANNEL,
  EARN5_PPRBS_INVALID_RATE,
  EARN5_PPRBS_RESYNC_FAILURE,

  /************** DO NOT ADD ERROR CODES BELOW THIS LINE ****************/
  EARN5_MAX_ERR_CODE
} earn5_error_enum_t ;


#define EARN5_OFST(x)    (x - EARN5_ERROR_CODE_BASE)


#endif /* __ARN5_ERROR_H__ */
