/******************************************************************************/
/**  COPYRIGHT (C) 2011 PMC-SIERRA, INC. ALL RIGHTS RESERVED.                **/
/**--------------------------------------------------------------------------**/
/** This software embodies materials and concepts which are proprietary and  **/
/** confidential to PMC-Sierra, Inc. PMC-Sierra distributes this software    **/
/** to its customers pursuant to the terms and conditions of the Software    **/
/** License Agreement contained in the text file software.lic that is        **/
/** distributed along with the software. This software can only be utilized  **/
/** if all terms and conditions of the Software License Agreement are        **/
/** accepted. If there are any questions, concerns, or if the                **/
/** Software License Agreement text file, software.lic, is missing please    **/
/** contact PMC-Sierra for assistance.                                       **/
/**--------------------------------------------------------------------------**/
/**                                                                          **/
/******************************************************************************/
/*******************************************************************************
**
**  MODULE      : HyPHY 20G Configuration Code
**
**  FILE        : hyphy20g_api_wrapper_hostmsg.c
**
**  DESCRIPTION : When building the hyphy20g driver codes with
**                HYPHY20G_API_REENTRANT_SUPPORT=YES defined, this file will
**                help provide reentrant APIs which can be called by mulitiple
**                applications(threads) at the same time.
**
**  NOTES       : hyphy20g_api_wrapper.h and hyphy20g_api_wrapper.c are both
**                generated by script file hyphy20g_api_wrapper.tcl.
**
**                Here a native API named hyPhy20gExampleAPI is taken as example
**                to describe how the reentrancy wrapping works.
**                For convenient, say the native non-reentrant hyPhy20gExampleAPI
**                is implemented in hyphy20g_example_api.c.
**                The following parts contribute to present the reentrant
**                hyPhy20gExampleAPI.
**                1)
**                In hyphy20g_api_wrapper.h, hyPhy20gExampleAPI is defined to
**                nr_hyPhy20gExampleAPI as below:
**                #define hyPhy20gExampleAPI nr_hyPhy20gExampleAPI
**
**                2)
**                The first active line of hyphy20g_example_api.c is:
**                #include "hyphy20g_api_wrapper.h"
**                Therefore, actually the hyPhy20gExampleAPI is renamed to
**                nr_hyPhy20gExampleAPI.
**
**                3)
**                In hyphy20g_api_wrapper.c, we generate automatically
**                the reentrant hyPhy20gExampleAPI as below:
**                extern INT4 nr_hyPhy20gExampleAPI(struct file *fileHndl);
**
**                INT4 hyPhy20gExampleAPI(struct file *fileHndl)
**                {
**                    INT4 ret;
**                    sHYPHY20G_CTXT *pDevCtxt;
**
**                    pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
**                    HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");
**
**                    sysHyPhy20gAtomicStart(pDevCtxt->sem);
**                    ret = nr_hyPhy20gExampleAPI(fileHndl);
**                    sysHyPhy20gAtomicEnd(pDevCtxt->sem);
**
**                    return ret;
**                }
**
*******************************************************************************/
#ifdef HYPHY20G_API_REENTRANT

#include    "hyphy20g_api.h"

/* Automatically generated codes, don't edit it! */
extern INT4 nr_hyPhy20gHostMsgChkObndDbelMskStatus(struct file *fileHndl, UINT4 doorBellNum, UINT4 status);

INT4 hyPhy20gHostMsgChkObndDbelMskStatus(struct file *fileHndl, UINT4 doorBellNum, UINT4 status)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgChkObndDbelMskStatus(fileHndl, doorBellNum, status);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgClrObndDbel(struct file *fileHndl, UINT4 doorBellNum);

INT4 hyPhy20gHostMsgClrObndDbel(struct file *fileHndl, UINT4 doorBellNum)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgClrObndDbel(fileHndl, doorBellNum);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSendLanToWanCmfHdlcFrm(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 type, UINT4 length, UINT4 pData[100]);

INT4 hyPhy20gHostMsgCmdCfgCsfSendLanToWanCmfHdlcFrm(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 type, UINT4 length, UINT4 pData[100])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSendLanToWanCmfHdlcFrm(fileHndl, gfpIdx, gfpChnl, type, length, pData);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSendLanToWanOneShotCmf(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 upi, UINT4 genPyldFcs, UINT4 cmfPyld[8]);

INT4 hyPhy20gHostMsgCmdCfgCsfSendLanToWanOneShotCmf(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 upi, UINT4 genPyldFcs, UINT4 cmfPyld[8])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSendLanToWanOneShotCmf(fileHndl, gfpIdx, gfpChnl, upi, genPyldFcs, cmfPyld);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetC2Byte(struct file *fileHndl, UINT4 vcatGrp, UINT4 thppMsk, UINT4 sts3Msk, UINT4 sts1Msk, UINT4 pdiP, UINT4 psl);

INT4 hyPhy20gHostMsgCmdCfgCsfSetC2Byte(struct file *fileHndl, UINT4 vcatGrp, UINT4 thppMsk, UINT4 sts3Msk, UINT4 sts1Msk, UINT4 pdiP, UINT4 psl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetC2Byte(fileHndl, vcatGrp, thppMsk, sts3Msk, sts1Msk, pdiP, psl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanConsActTable(struct file *fileHndl, UINT4 tableIdx, UINT4 losMonVAct, UINT4 rxDlolLsciMonVAct, UINT4 rxDlolHsciMonVAct, UINT4 rxGbeLosSyncVAct, UINT4 rxGsup73LosSyncVAct, UINT4 rxGsup73HberVAct, UINT4 rxGsup73LnkFailVAct, UINT4 rxFeLosSyncVAct, UINT4 rxFeFiVAct, UINT4 swAlarmVAct, UINT4 rxFeGeLnkFailVAct, UINT4 priority1Act, UINT4 priority2Act, UINT4 priority3Act, UINT4 priority4Act, UINT4 priority5Act, UINT4 priority6Act);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanConsActTable(struct file *fileHndl, UINT4 tableIdx, UINT4 losMonVAct, UINT4 rxDlolLsciMonVAct, UINT4 rxDlolHsciMonVAct, UINT4 rxGbeLosSyncVAct, UINT4 rxGsup73LosSyncVAct, UINT4 rxGsup73HberVAct, UINT4 rxGsup73LnkFailVAct, UINT4 rxFeLosSyncVAct, UINT4 rxFeFiVAct, UINT4 swAlarmVAct, UINT4 rxFeGeLnkFailVAct, UINT4 priority1Act, UINT4 priority2Act, UINT4 priority3Act, UINT4 priority4Act, UINT4 priority5Act, UINT4 priority6Act)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanConsActTable(fileHndl, tableIdx, losMonVAct, rxDlolLsciMonVAct, rxDlolHsciMonVAct, rxGbeLosSyncVAct, rxGsup73LosSyncVAct, rxGsup73HberVAct, rxGsup73LnkFailVAct, rxFeLosSyncVAct, rxFeFiVAct, swAlarmVAct, rxFeGeLnkFailVAct, priority1Act, priority2Act, priority3Act, priority4Act, priority5Act, priority6Act);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanCsfFrmGenInt(struct file *fileHndl, UINT4 interval);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanCsfFrmGenInt(struct file *fileHndl, UINT4 interval)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanCsfFrmGenInt(fileHndl, interval);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortActTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 tableIdx, UINT4 sendDci, UINT4 exi, UINT4 cid, UINT4 eHec, UINT4 genKpAlvCmf, UINT4 usePyld, UINT4 genPyldFcs, UINT4 upi, UINT4 cmfPyld[8]);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortActTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 tableIdx, UINT4 sendDci, UINT4 exi, UINT4 cid, UINT4 eHec, UINT4 genKpAlvCmf, UINT4 usePyld, UINT4 genPyldFcs, UINT4 upi, UINT4 cmfPyld[8])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortActTable(fileHndl, chnlType, chnlId, tableIdx, sendDci, exi, cid, eHec, genKpAlvCmf, usePyld, genPyldFcs, upi, cmfPyld);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortMapTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 serdes, UINT4 vcatGrp);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortMapTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 serdes, UINT4 vcatGrp)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanPortMapTable(fileHndl, chnlType, chnlId, gfpIdx, gfpChnl, serdes, vcatGrp);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanSoftAlarmForce(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanSoftAlarmForce(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanSoftAlarmForce(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanUpdateTblNotif(struct file *fileHndl, UINT4 hsciChnlUpdateMsk, UINT4 lsciChnlUpdateMsk);

INT4 hyPhy20gHostMsgCmdCfgCsfSetLanToWanUpdateTblNotif(struct file *fileHndl, UINT4 hsciChnlUpdateMsk, UINT4 lsciChnlUpdateMsk)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetLanToWanUpdateTblNotif(fileHndl, hsciChnlUpdateMsk, lsciChnlUpdateMsk);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanCmfRetrOption(struct file *fileHndl, UINT4 mode);

INT4 hyPhy20gHostMsgCmdCfgCsfSetWanToLanCmfRetrOption(struct file *fileHndl, UINT4 mode)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanCmfRetrOption(fileHndl, mode);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanMapTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 action, UINT4 upi);

INT4 hyPhy20gHostMsgCmdCfgCsfSetWanToLanMapTable(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 action, UINT4 upi)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanMapTable(fileHndl, chnlType, chnlId, gfpIdx, gfpChnl, action, upi);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanSetDefCondStopParam(struct file *fileHndl, UINT4 interval);

INT4 hyPhy20gHostMsgCmdCfgCsfSetWanToLanSetDefCondStopParam(struct file *fileHndl, UINT4 interval)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanSetDefCondStopParam(fileHndl, interval);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanSoftConseqForce(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 forceCtrl);

INT4 hyPhy20gHostMsgCmdCfgCsfSetWanToLanSoftConseqForce(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 forceCtrl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanSoftConseqForce(fileHndl, chnlType, chnlId, forceCtrl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanUpdateTblNotif(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl);

INT4 hyPhy20gHostMsgCmdCfgCsfSetWanToLanUpdateTblNotif(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgCsfSetWanToLanUpdateTblNotif(fileHndl, gfpIdx, gfpChnl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetEnetMpFilterSetup(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 pktType, UINT4 vlanTpid, UINT4 vlanTci, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgEnetMpFilterSetEnetMpFilterSetup(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 pktType, UINT4 vlanTpid, UINT4 vlanTci, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetEnetMpFilterSetup(fileHndl, chnlType, chnlId, pktType, vlanTpid, vlanTci, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattCtrl(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattParam(struct file *fileHndl, UINT4 macAddr[6], UINT4 pattType, UINT4 pattData, UINT4 pyldSize);

INT4 hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattParam(struct file *fileHndl, UINT4 macAddr[6], UINT4 pattType, UINT4 pattData, UINT4 pyldSize)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgEnetMpFilterSetTestPattParam(fileHndl, macAddr, pattType, pattData, pyldSize);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLedSetHsciMap(struct file *fileHndl, UINT4 map);

INT4 hyPhy20gHostMsgCmdCfgLedSetHsciMap(struct file *fileHndl, UINT4 map)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLedSetHsciMap(fileHndl, map);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLedSetMonCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 clientType, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgLedSetMonCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 clientType, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLedSetMonCtrl(fileHndl, chnlType, chnlId, clientType, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLedSetTwiAddrSetup(struct file *fileHndl, UINT4 devAddr, UINT4 memAddr);

INT4 hyPhy20gHostMsgCmdCfgLedSetTwiAddrSetup(struct file *fileHndl, UINT4 devAddr, UINT4 memAddr)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLedSetTwiAddrSetup(fileHndl, devAddr, memAddr);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamCfgChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 varRetrSup, UINT4 lnkEvntSup, UINT4 lpbkSup, UINT4 uniDirSup, UINT4 mode, UINT4 rate, UINT4 pduMaxSize);

INT4 hyPhy20gHostMsgCmdCfgLnkOamCfgChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 varRetrSup, UINT4 lnkEvntSup, UINT4 lpbkSup, UINT4 uniDirSup, UINT4 mode, UINT4 rate, UINT4 pduMaxSize)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamCfgChnl(fileHndl, chnlType, chnlId, varRetrSup, lnkEvntSup, lpbkSup, uniDirSup, mode, rate, pduMaxSize);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamCtrlChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgLnkOamCtrlChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamCtrlChnl(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamLocEvntCfg(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 symPerEvntWinMsw, UINT4 symPerEvntWinLsw, UINT4 symPerEvntThreshMsw, UINT4 symPerEvntThreshLsw, UINT4 frmEvntWin, UINT4 frmEvntThresh, UINT4 frmPerEvntWin, UINT4 frmPerEvntThresh, UINT4 frmSecSumEvntWin, UINT4 frmSecSumEvntThresh);

INT4 hyPhy20gHostMsgCmdCfgLnkOamLocEvntCfg(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 symPerEvntWinMsw, UINT4 symPerEvntWinLsw, UINT4 symPerEvntThreshMsw, UINT4 symPerEvntThreshLsw, UINT4 frmEvntWin, UINT4 frmEvntThresh, UINT4 frmPerEvntWin, UINT4 frmPerEvntThresh, UINT4 frmSecSumEvntWin, UINT4 frmSecSumEvntThresh)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamLocEvntCfg(fileHndl, chnlType, chnlId, symPerEvntWinMsw, symPerEvntWinLsw, symPerEvntThreshMsw, symPerEvntThreshLsw, frmEvntWin, frmEvntThresh, frmPerEvntWin, frmPerEvntThresh, frmSecSumEvntWin, frmSecSumEvntThresh);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamSendMibVarReq(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 branch, UINT4 leaf);

INT4 hyPhy20gHostMsgCmdCfgLnkOamSendMibVarReq(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 branch, UINT4 leaf)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamSendMibVarReq(fileHndl, chnlType, chnlId, branch, leaf);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamSetCritEvntNotf(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 critEvnt);

INT4 hyPhy20gHostMsgCmdCfgLnkOamSetCritEvntNotf(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 critEvnt)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamSetCritEvntNotf(fileHndl, chnlType, chnlId, critEvnt);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamSetLocalMibVar(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 branch, UINT4 leaf, UINT4 varInd, UINT4 varIndVal, UINT4 valueLen, UINT1 *pValue);

INT4 hyPhy20gHostMsgCmdCfgLnkOamSetLocalMibVar(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 branch, UINT4 leaf, UINT4 varInd, UINT4 varIndVal, UINT4 valueLen, UINT1 *pValue)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamSetLocalMibVar(fileHndl, chnlType, chnlId, branch, leaf, varInd, varIndVal, valueLen, pValue);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgLnkOamSetLpbk(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 lpbkType, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgLnkOamSetLpbk(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 lpbkType, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgLnkOamSetLpbk(fileHndl, chnlType, chnlId, lpbkType, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPmonEnetStatColCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgPmonEnetStatColCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPmonEnetStatColCtrl(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPmonReleaseMstatxCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId);

INT4 hyPhy20gHostMsgCmdCfgPmonReleaseMstatxCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPmonReleaseMstatxCtrl(fileHndl, chnlType, chnlId);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPmonReqMstatxCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId);

INT4 hyPhy20gHostMsgCmdCfgPmonReqMstatxCtrl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPmonReqMstatxCtrl(fileHndl, chnlType, chnlId);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetAccptMstrClks(struct file *fileHndl, UINT4 enableTable, UINT4 clearTable, UINT4 numEntries, UINT4 clkIdMsw[20], UINT4 clkIdLsw[20], UINT4 portNum[20]);

INT4 hyPhy20gHostMsgCmdCfgPtpSetAccptMstrClks(struct file *fileHndl, UINT4 enableTable, UINT4 clearTable, UINT4 numEntries, UINT4 clkIdMsw[20], UINT4 clkIdLsw[20], UINT4 portNum[20])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetAccptMstrClks(fileHndl, enableTable, clearTable, numEntries, clkIdMsw, clkIdLsw, portNum);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetClkParam(struct file *fileHndl, UINT4 clkType, UINT4 twoStepFlg, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 domainNum, UINT4 protocol, UINT4 operatingMode, UINT4 multiEnable);

INT4 hyPhy20gHostMsgCmdCfgPtpSetClkParam(struct file *fileHndl, UINT4 clkType, UINT4 twoStepFlg, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 domainNum, UINT4 protocol, UINT4 operatingMode, UINT4 multiEnable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetClkParam(fileHndl, clkType, twoStepFlg, clkIdMsw, clkIdLsw, domainNum, protocol, operatingMode, multiEnable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetDefaultProp(struct file *fileHndl, UINT4 clkClass, UINT4 clkAccuracy, UINT4 logVar, UINT4 priority1, UINT4 priority2, UINT4 slaveOnly);

INT4 hyPhy20gHostMsgCmdCfgPtpSetDefaultProp(struct file *fileHndl, UINT4 clkClass, UINT4 clkAccuracy, UINT4 logVar, UINT4 priority1, UINT4 priority2, UINT4 slaveOnly)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetDefaultProp(fileHndl, clkClass, clkAccuracy, logVar, priority1, priority2, slaveOnly);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetIPv4Param(struct file *fileHndl, UINT4 precedence, UINT4 delay, UINT4 throughput, UINT4 reliability, UINT4 ttl, UINT4 srcAddr[4], UINT4 destAddr[4]);

INT4 hyPhy20gHostMsgCmdCfgPtpSetIPv4Param(struct file *fileHndl, UINT4 precedence, UINT4 delay, UINT4 throughput, UINT4 reliability, UINT4 ttl, UINT4 srcAddr[4], UINT4 destAddr[4])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetIPv4Param(fileHndl, precedence, delay, throughput, reliability, ttl, srcAddr, destAddr);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetIPv6Param(struct file *fileHndl, UINT4 trfClass, UINT4 flowLabel, UINT4 hopLimit, UINT4 daScopeVal, UINT4 srcAddr[8], UINT4 destAddr[8]);

INT4 hyPhy20gHostMsgCmdCfgPtpSetIPv6Param(struct file *fileHndl, UINT4 trfClass, UINT4 flowLabel, UINT4 hopLimit, UINT4 daScopeVal, UINT4 srcAddr[8], UINT4 destAddr[8])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetIPv6Param(fileHndl, trfClass, flowLabel, hopLimit, daScopeVal, srcAddr, destAddr);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetIrigCfg(struct file *fileHndl, UINT4 irigPort, UINT4 irigMode, UINT4 adjMode, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgPtpSetIrigCfg(struct file *fileHndl, UINT4 irigPort, UINT4 irigMode, UINT4 adjMode, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetIrigCfg(fileHndl, irigPort, irigMode, adjMode, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetParentData(struct file *fileHndl, UINT4 stepsRemoved, UINT4 parentClkIdMsw, UINT4 parentClkIdLsw, UINT4 parentPortNum, UINT4 gmPriority1, UINT4 gmPriority2, UINT4 gmClkClass, UINT4 gmClkAccu, UINT4 gmLogVar, UINT4 gmClkIdMsw, UINT4 gmClkIdLsw, UINT4 unicastDA[6]);

INT4 hyPhy20gHostMsgCmdCfgPtpSetParentData(struct file *fileHndl, UINT4 stepsRemoved, UINT4 parentClkIdMsw, UINT4 parentClkIdLsw, UINT4 parentPortNum, UINT4 gmPriority1, UINT4 gmPriority2, UINT4 gmClkClass, UINT4 gmClkAccu, UINT4 gmLogVar, UINT4 gmClkIdMsw, UINT4 gmClkIdLsw, UINT4 unicastDA[6])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetParentData(fileHndl, stepsRemoved, parentClkIdMsw, parentClkIdLsw, parentPortNum, gmPriority1, gmPriority2, gmClkClass, gmClkAccu, gmLogVar, gmClkIdMsw, gmClkIdLsw, unicastDA);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPartialPtpParam(struct file *fileHndl, UINT4 exterInterface, UINT4 vlanTci, UINT4 rxTimestamp, UINT4 eventFeedback, UINT4 hostMacAddr[6], UINT4 mipsMacAddr[6], UINT4 vlanPresent);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPartialPtpParam(struct file *fileHndl, UINT4 exterInterface, UINT4 vlanTci, UINT4 rxTimestamp, UINT4 eventFeedback, UINT4 hostMacAddr[6], UINT4 mipsMacAddr[6], UINT4 vlanPresent)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPartialPtpParam(fileHndl, exterInterface, vlanTci, rxTimestamp, eventFeedback, hostMacAddr, mipsMacAddr, vlanPresent);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPassPortParent(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 portNum);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPassPortParent(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 portNum)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPassPortParent(fileHndl, chnlType, chnlId, clkIdMsw, clkIdLsw, portNum);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPortAsymmetry(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 delayAsymmetry, UINT4 rxStaticOffset, UINT4 txStaticOffset);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPortAsymmetry(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 delayAsymmetry, UINT4 rxStaticOffset, UINT4 txStaticOffset)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPortAsymmetry(fileHndl, chnlType, chnlId, delayAsymmetry, rxStaticOffset, txStaticOffset);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPortData(struct file *fileHndl, UINT4 logMinDlyReq, UINT4 logAnnounce, UINT4 announceRecTimeout, UINT4 logSync, UINT4 dlyMech, UINT4 logMinPDlyReq, UINT4 qualTimeoutN, UINT4 syncRecTimeout, UINT4 dlyRespRecTimeout);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPortData(struct file *fileHndl, UINT4 logMinDlyReq, UINT4 logAnnounce, UINT4 announceRecTimeout, UINT4 logSync, UINT4 dlyMech, UINT4 logMinPDlyReq, UINT4 qualTimeoutN, UINT4 syncRecTimeout, UINT4 dlyRespRecTimeout)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPortData(fileHndl, logMinDlyReq, logAnnounce, announceRecTimeout, logSync, dlyMech, logMinPDlyReq, qualTimeoutN, syncRecTimeout, dlyRespRecTimeout);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPortEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPortEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPortEvnt(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetPortState(struct file *fileHndl, UINT4 lsciState0, UINT4 lsciState1, UINT4 lsciState2, UINT4 lsciState3, UINT4 lsciState4, UINT4 lsciState5, UINT4 lsciState6, UINT4 lsciState7, UINT4 lsciState8, UINT4 lsciState9, UINT4 lsciState10, UINT4 lsciState11, UINT4 lsciState12, UINT4 lsciState13, UINT4 lsciState14, UINT4 lsciState15, UINT4 hsciState0, UINT4 hsciState1);

INT4 hyPhy20gHostMsgCmdCfgPtpSetPortState(struct file *fileHndl, UINT4 lsciState0, UINT4 lsciState1, UINT4 lsciState2, UINT4 lsciState3, UINT4 lsciState4, UINT4 lsciState5, UINT4 lsciState6, UINT4 lsciState7, UINT4 lsciState8, UINT4 lsciState9, UINT4 lsciState10, UINT4 lsciState11, UINT4 lsciState12, UINT4 lsciState13, UINT4 lsciState14, UINT4 lsciState15, UINT4 hsciState0, UINT4 hsciState1)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetPortState(fileHndl, lsciState0, lsciState1, lsciState2, lsciState3, lsciState4, lsciState5, lsciState6, lsciState7, lsciState8, lsciState9, lsciState10, lsciState11, lsciState12, lsciState13, lsciState14, lsciState15, hsciState0, hsciState1);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetStartInit(struct file *fileHndl, UINT4 lsciPortInit, UINT4 hsciPortInit);

INT4 hyPhy20gHostMsgCmdCfgPtpSetStartInit(struct file *fileHndl, UINT4 lsciPortInit, UINT4 hsciPortInit)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetStartInit(fileHndl, lsciPortInit, hsciPortInit);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetTcParam(struct file *fileHndl, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 portNum, UINT4 syntEnable, UINT4 lsciChnlEnable, UINT4 hsciChnlEnable);

INT4 hyPhy20gHostMsgCmdCfgPtpSetTcParam(struct file *fileHndl, UINT4 clkIdMsw, UINT4 clkIdLsw, UINT4 portNum, UINT4 syntEnable, UINT4 lsciChnlEnable, UINT4 hsciChnlEnable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetTcParam(fileHndl, clkIdMsw, clkIdLsw, portNum, syntEnable, lsciChnlEnable, hsciChnlEnable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetTcPortParam(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 logMinPDlyReq);

INT4 hyPhy20gHostMsgCmdCfgPtpSetTcPortParam(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 logMinPDlyReq)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetTcPortParam(fileHndl, chnlType, chnlId, logMinPDlyReq);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetTimeProp(struct file *fileHndl, UINT4 utcOffset, UINT4 leap, UINT4 utcOffValid, UINT4 ptpTimescale, UINT4 timeTraceable, UINT4 freqTraceable, UINT4 timeSrc);

INT4 hyPhy20gHostMsgCmdCfgPtpSetTimeProp(struct file *fileHndl, UINT4 utcOffset, UINT4 leap, UINT4 utcOffValid, UINT4 ptpTimescale, UINT4 timeTraceable, UINT4 freqTraceable, UINT4 timeSrc)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetTimeProp(fileHndl, utcOffset, leap, utcOffValid, ptpTimescale, timeTraceable, freqTraceable, timeSrc);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastCancel(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 msgType);

INT4 hyPhy20gHostMsgCmdCfgPtpSetUnicastCancel(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 msgType)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastCancel(fileHndl, chnlType, chnlId, msgType);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastMasterParam(struct file *fileHndl, UINT4 logIntMsgPeriod[3], UINT4 durationField[3]);

INT4 hyPhy20gHostMsgCmdCfgPtpSetUnicastMasterParam(struct file *fileHndl, UINT4 logIntMsgPeriod[3], UINT4 durationField[3])
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastMasterParam(fileHndl, logIntMsgPeriod, durationField);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastReq(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 msgType, UINT4 logIntMsgPeriod[3], UINT4 durationField[3], UINT4 continuous, UINT4 indTlv);

INT4 hyPhy20gHostMsgCmdCfgPtpSetUnicastReq(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 msgType, UINT4 logIntMsgPeriod[3], UINT4 durationField[3], UINT4 continuous, UINT4 indTlv)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgPtpSetUnicastReq(fileHndl, chnlType, chnlId, msgType, logIntMsgPeriod, durationField, continuous, indTlv);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgSerdesSetEquTap(struct file *fileHndl, UINT4 groupNum, UINT4 linkNum, UINT4 numIter);

INT4 hyPhy20gHostMsgCmdCfgSerdesSetEquTap(struct file *fileHndl, UINT4 groupNum, UINT4 linkNum, UINT4 numIter)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgSerdesSetEquTap(fileHndl, groupNum, linkNum, numIter);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgSyncECfgChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 mode, UINT4 qlSSM);

INT4 hyPhy20gHostMsgCmdCfgSyncECfgChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 mode, UINT4 qlSSM)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgSyncECfgChnl(fileHndl, chnlType, chnlId, mode, qlSSM);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgSyncECtrlChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable);

INT4 hyPhy20gHostMsgCmdCfgSyncECtrlChnl(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgSyncECtrlChnl(fileHndl, chnlType, chnlId, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgSyncETxSSM(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 evntFlag, UINT4 qlSSM);

INT4 hyPhy20gHostMsgCmdCfgSyncETxSSM(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 evntFlag, UINT4 qlSSM)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgSyncETxSSM(fileHndl, chnlType, chnlId, evntFlag, qlSSM);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgVcatLcasSetDefectCollectCtrl(struct file *fileHndl, UINT4 defectColCtrl);

INT4 hyPhy20gHostMsgCmdCfgVcatLcasSetDefectCollectCtrl(struct file *fileHndl, UINT4 defectColCtrl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgVcatLcasSetDefectCollectCtrl(fileHndl, defectColCtrl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgVcatLcasSetForceState(struct file *fileHndl, UINT4 sts48Num, UINT4 sts12Num, UINT4 sts3Num, UINT4 sts1Num, UINT4 defectType, UINT4 enable, UINT4 state);

INT4 hyPhy20gHostMsgCmdCfgVcatLcasSetForceState(struct file *fileHndl, UINT4 sts48Num, UINT4 sts12Num, UINT4 sts3Num, UINT4 sts1Num, UINT4 defectType, UINT4 enable, UINT4 state)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgVcatLcasSetForceState(fileHndl, sts48Num, sts12Num, sts3Num, sts1Num, defectType, enable, state);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgVcatLcasSetHeartbeat(struct file *fileHndl);

INT4 hyPhy20gHostMsgCmdCfgVcatLcasSetHeartbeat(struct file *fileHndl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgVcatLcasSetHeartbeat(fileHndl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdCfgVcatLcasSetStateMachineCtrl(struct file *fileHndl, UINT4 sts48Num, UINT4 sts12Num, UINT4 sts3Num, UINT4 sts1Num, UINT4 smCtrl);

INT4 hyPhy20gHostMsgCmdCfgVcatLcasSetStateMachineCtrl(struct file *fileHndl, UINT4 sts48Num, UINT4 sts12Num, UINT4 sts3Num, UINT4 sts1Num, UINT4 smCtrl)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdCfgVcatLcasSetStateMachineCtrl(fileHndl, sts48Num, sts12Num, sts3Num, sts1Num, smCtrl);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetLanToWanConsActStat(struct file *fileHndl, UINT4 *pHsci, UINT4 *pLsci);

INT4 hyPhy20gHostMsgCmdReqCsfGetLanToWanConsActStat(struct file *fileHndl, UINT4 *pHsci, UINT4 *pLsci)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetLanToWanConsActStat(fileHndl, pHsci, pLsci);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetRxFefiStat(struct file *fileHndl, UINT4 lsciChStat, UINT4 *pLsciChStat, UINT4 *pLsciFefiStat);

INT4 hyPhy20gHostMsgCmdReqCsfGetRxFefiStat(struct file *fileHndl, UINT4 lsciChStat, UINT4 *pLsciChStat, UINT4 *pLsciFefiStat)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetRxFefiStat(fileHndl, lsciChStat, pLsciChStat, pLsciFefiStat);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanCmfInd(struct file *fileHndl, UINT4 gfpIdx, UINT4 *pUpiGfp);

INT4 hyPhy20gHostMsgCmdReqCsfGetWanToLanCmfInd(struct file *fileHndl, UINT4 gfpIdx, UINT4 *pUpiGfp)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanCmfInd(fileHndl, gfpIdx, pUpiGfp);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanConsActStat(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pForceCtrl, UINT4 *pActionNum);

INT4 hyPhy20gHostMsgCmdReqCsfGetWanToLanConsActStat(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pForceCtrl, UINT4 *pActionNum)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanConsActStat(fileHndl, chnlType, chnlId, pChnlType, pChnlId, pForceCtrl, pActionNum);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanOneShotKeepAliveCmfMultiCh( struct file *fileHndl, UINT4 chnlCnt, UINT4 chnlSlc[15], UINT4 chnlNum[15], UINT4 *pChnlCnt, UINT4 *pChnlData);

INT4 hyPhy20gHostMsgCmdReqCsfGetWanToLanOneShotKeepAliveCmfMultiCh( struct file *fileHndl, UINT4 chnlCnt, UINT4 chnlSlc[15], UINT4 chnlNum[15], UINT4 *pChnlCnt, UINT4 *pChnlData)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanOneShotKeepAliveCmfMultiCh(fileHndl, chnlCnt, chnlSlc, chnlNum, pChnlCnt, pChnlData);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanPropCmf(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 *pGfpIdx, UINT4 *pGfpChnl, UINT4 *pUpiType, UINT4 *pLength, UINT4 *pData);

INT4 hyPhy20gHostMsgCmdReqCsfGetWanToLanPropCmf(struct file *fileHndl, UINT4 gfpIdx, UINT4 gfpChnl, UINT4 *pGfpIdx, UINT4 *pGfpChnl, UINT4 *pUpiType, UINT4 *pLength, UINT4 *pData)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqCsfGetWanToLanPropCmf(fileHndl, gfpIdx, gfpChnl, pGfpIdx, pGfpChnl, pUpiType, pLength, pData);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqEnetMpFilterGetTestPktStatus(struct file *fileHndl, UINT4 *pPattType, UINT4 *pPattData, UINT4 *pPyldSize, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pEnable, UINT4 *pNumTxPkt, UINT4 *pNumRxPkt, UINT4 *pNumRxErrPkt);

INT4 hyPhy20gHostMsgCmdReqEnetMpFilterGetTestPktStatus(struct file *fileHndl, UINT4 *pPattType, UINT4 *pPattData, UINT4 *pPyldSize, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pEnable, UINT4 *pNumTxPkt, UINT4 *pNumRxPkt, UINT4 *pNumRxErrPkt)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqEnetMpFilterGetTestPktStatus(fileHndl, pPattType, pPattData, pPyldSize, pChnlType, pChnlId, pEnable, pNumTxPkt, pNumRxPkt, pNumRxErrPkt);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqGetHsciGsup43PmonCntr(struct file *fileHndl, UINT4 chnlId, UINT4 *pCount0, UINT4 *pCount1, UINT4 *pCount2, UINT4 *pCount3, UINT4 *pCount4, UINT4 *pCount5, UINT4 *pCount6, UINT4 *pCount7, UINT4 *pCount8, UINT4 *pCount9, UINT4 *pCount10, UINT4 *pCount11, UINT4 *pOverflowI);

INT4 hyPhy20gHostMsgCmdReqGetHsciGsup43PmonCntr(struct file *fileHndl, UINT4 chnlId, UINT4 *pCount0, UINT4 *pCount1, UINT4 *pCount2, UINT4 *pCount3, UINT4 *pCount4, UINT4 *pCount5, UINT4 *pCount6, UINT4 *pCount7, UINT4 *pCount8, UINT4 *pCount9, UINT4 *pCount10, UINT4 *pCount11, UINT4 *pOverflowI)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqGetHsciGsup43PmonCntr(fileHndl, chnlId, pCount0, pCount1, pCount2, pCount3, pCount4, pCount5, pCount6, pCount7, pCount8, pCount9, pCount10, pCount11, pOverflowI);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqGetLsciL1RppPmonCntr(struct file *fileHndl, UINT4 chnlId, UINT4 *pCount, UINT4 *pOverflowI);

INT4 hyPhy20gHostMsgCmdReqGetLsciL1RppPmonCntr(struct file *fileHndl, UINT4 chnlId, UINT4 *pCount, UINT4 *pOverflowI)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqGetLsciL1RppPmonCntr(fileHndl, chnlId, pCount, pOverflowI);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqGetMstrClkDbStatus(struct file *fileHndl, UINT4 *status, UINT4 *numEntries);

INT4 hyPhy20gHostMsgCmdReqGetMstrClkDbStatus(struct file *fileHndl, UINT4 *status, UINT4 *numEntries)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqGetMstrClkDbStatus(fileHndl, status, numEntries);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqInfoGetStatus(struct file *fileHndl, UINT4 statCtrl, UINT4 *statType, UINT4 *statCode);

INT4 hyPhy20gHostMsgCmdReqInfoGetStatus(struct file *fileHndl, UINT4 statCtrl, UINT4 *statType, UINT4 *statCode)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqInfoGetStatus(fileHndl, statCtrl, statType, statCode);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqInfoGetVerInfo(struct file *fileHndl, UINT4 control, UINT4 *revNum, UINT4 *buildNum);

INT4 hyPhy20gHostMsgCmdReqInfoGetVerInfo(struct file *fileHndl, UINT4 control, UINT4 *revNum, UINT4 *buildNum)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqInfoGetVerInfo(fileHndl, control, revNum, buildNum);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqLnkOamGetInfo(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *rspCtrl, UINT4 *rspLCfg, UINT4 *rspRCfg, UINT4 *rspLState, UINT4 *rspRState, UINT4 *rspLCritEvnt, UINT4 *rspRCritEvnt, UINT4 *rspMibReqCnt, UINT4 *rspMibRspCnt, UINT4 *rspRate, UINT4 *rspPduMaxSize, UINT4 *rspBranch0, UINT4 *rspLeaf0, UINT4 *rspBranch1, UINT4 *rspLeaf1, UINT4 *rspBranch2, UINT4 *rspLeaf2, UINT4 *rspBranch3, UINT4 *rspLeaf3);

INT4 hyPhy20gHostMsgCmdReqLnkOamGetInfo(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *rspCtrl, UINT4 *rspLCfg, UINT4 *rspRCfg, UINT4 *rspLState, UINT4 *rspRState, UINT4 *rspLCritEvnt, UINT4 *rspRCritEvnt, UINT4 *rspMibReqCnt, UINT4 *rspMibRspCnt, UINT4 *rspRate, UINT4 *rspPduMaxSize, UINT4 *rspBranch0, UINT4 *rspLeaf0, UINT4 *rspBranch1, UINT4 *rspLeaf1, UINT4 *rspBranch2, UINT4 *rspLeaf2, UINT4 *rspBranch3, UINT4 *rspLeaf3)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqLnkOamGetInfo(fileHndl, chnlType, chnlId, rspCtrl, rspLCfg, rspRCfg, rspLState, rspRState, rspLCritEvnt, rspRCritEvnt, rspMibReqCnt, rspMibRspCnt, rspRate, rspPduMaxSize, rspBranch0, rspLeaf0, rspBranch1, rspLeaf1, rspBranch2, rspLeaf2, rspBranch3, rspLeaf3);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqLnkOamGetLocalLnkEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pTLV0, UINT4 *pTLV1, UINT4 *pTLV2, UINT4 *pTLV3);

INT4 hyPhy20gHostMsgCmdReqLnkOamGetLocalLnkEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pTLV0, UINT4 *pTLV1, UINT4 *pTLV2, UINT4 *pTLV3)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqLnkOamGetLocalLnkEvnt(fileHndl, chnlType, chnlId, pTLV0, pTLV1, pTLV2, pTLV3);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqLnkOamGetRemoteLnkEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pTLV0, UINT4 *pTLV1, UINT4 *pTLV2, UINT4 *pTLV3);

INT4 hyPhy20gHostMsgCmdReqLnkOamGetRemoteLnkEvnt(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pTLV0, UINT4 *pTLV1, UINT4 *pTLV2, UINT4 *pTLV3)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqLnkOamGetRemoteLnkEvnt(fileHndl, chnlType, chnlId, pTLV0, pTLV1, pTLV2, pTLV3);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqLnkOamGetRemoteMibVar(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *branch, UINT4 *leaf, UINT4 *width, UINT4 *valueLen, UINT4 *value);

INT4 hyPhy20gHostMsgCmdReqLnkOamGetRemoteMibVar(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *branch, UINT4 *leaf, UINT4 *width, UINT4 *valueLen, UINT4 *value)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqLnkOamGetRemoteMibVar(fileHndl, chnlType, chnlId, branch, leaf, width, valueLen, value);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqPtpGetMstrClkDb(struct file *fileHndl, UINT4 *pRspLength, UINT4 *pMstrClkDb);

INT4 hyPhy20gHostMsgCmdReqPtpGetMstrClkDb(struct file *fileHndl, UINT4 *pRspLength, UINT4 *pMstrClkDb)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqPtpGetMstrClkDb(fileHndl, pRspLength, pMstrClkDb);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqPtpGetPathDelay(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pathDelay);

INT4 hyPhy20gHostMsgCmdReqPtpGetPathDelay(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pathDelay)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqPtpGetPathDelay(fileHndl, chnlType, chnlId, pathDelay);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqPtpGetPortRxMsgCnts(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pCnts);

INT4 hyPhy20gHostMsgCmdReqPtpGetPortRxMsgCnts(struct file *fileHndl, UINT4 chnlType, UINT4 chnlId, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pCnts)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqPtpGetPortRxMsgCnts(fileHndl, chnlType, chnlId, pChnlType, pChnlId, pCnts);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqPtpGetPortState(struct file *fileHndl, UINT4 *pPortStates);

INT4 hyPhy20gHostMsgCmdReqPtpGetPortState(struct file *fileHndl, UINT4 *pPortStates)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqPtpGetPortState(fileHndl, pPortStates);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqPtpGetUnicastSlvStat(struct file *fileHndl, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pLogIntMsgPeriod, UINT4 *pDurationField);

INT4 hyPhy20gHostMsgCmdReqPtpGetUnicastSlvStat(struct file *fileHndl, UINT4 *pChnlType, UINT4 *pChnlId, UINT4 *pLogIntMsgPeriod, UINT4 *pDurationField)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqPtpGetUnicastSlvStat(fileHndl, pChnlType, pChnlId, pLogIntMsgPeriod, pDurationField);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqSyncEGetSSM(struct file *fileHndl, UINT4 *pObndMsgBodyLen, UINT4 *pObndMsgBody);

INT4 hyPhy20gHostMsgCmdReqSyncEGetSSM(struct file *fileHndl, UINT4 *pObndMsgBodyLen, UINT4 *pObndMsgBody)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqSyncEGetSSM(fileHndl, pObndMsgBodyLen, pObndMsgBody);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntInd(struct file *fileHndl, UINT4 reqCtrl, UINT4 *pIntData);

INT4 hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntInd(struct file *fileHndl, UINT4 reqCtrl, UINT4 *pIntData)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntInd(fileHndl, reqCtrl, pIntData);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntStatus(struct file *fileHndl, UINT4 *pIntData);

INT4 hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntStatus(struct file *fileHndl, UINT4 *pIntData)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectIntStatus(fileHndl, pIntData);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectState(struct file *fileHndl, UINT4 reqCtrl, UINT4 *pState);

INT4 hyPhy20gHostMsgCmdReqVcatLcasGetDefectState(struct file *fileHndl, UINT4 reqCtrl, UINT4 *pState)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqVcatLcasGetDefectState(fileHndl, reqCtrl, pState);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgCmdReqVcatLcasGetLinkStatus(struct file *fileHndl, UINT4 *pStatus);

INT4 hyPhy20gHostMsgCmdReqVcatLcasGetLinkStatus(struct file *fileHndl, UINT4 *pStatus)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgCmdReqVcatLcasGetLinkStatus(fileHndl, pStatus);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgFwOp(struct file *fileHndl, UINT4 enable);

INT4 hyPhy20gHostMsgFwOp(struct file *fileHndl, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgFwOp(fileHndl, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgInit(struct file *fileHndl, UINT4 enable);

INT4 hyPhy20gHostMsgInit(struct file *fileHndl, UINT4 enable)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgInit(fileHndl, enable);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}

extern INT4 nr_hyPhy20gHostMsgPollObndDbelMskStatus(struct file *fileHndl, UINT4 doorBellNum, UINT4 status, UINT4 msDelay);

INT4 hyPhy20gHostMsgPollObndDbelMskStatus(struct file *fileHndl, UINT4 doorBellNum, UINT4 status, UINT4 msDelay)
{
	INT4 ret;
	sHYPHY20G_CTXT *pDevCtxt;

	pDevCtxt = sysHyPhy20gGetDeviceCtxt(fileHndl);
	HYPHY20G_ASSERT((pDevCtxt != NULL), HYPHY20G_ERR_NULL_PTR_PASSED, "%s", "pDevCtxt or pDevCtxt->pCpbCtxt is NULL.");

	sysHyPhy20gAtomicStart(pDevCtxt->sem);
	ret = nr_hyPhy20gHostMsgPollObndDbelMskStatus(fileHndl, doorBellNum, status, msDelay);
	sysHyPhy20gAtomicEnd(pDevCtxt->sem);

	return ret;
}


#endif
/* end of file */
