/******************************************************************************/
/**  COPYRIGHT (C) 2008 PMC-SIERRA, INC. ALL RIGHTS RESERVED.                **/
/**--------------------------------------------------------------------------**/
/** This software embodies materials and concepts which are proprietary and  **/
/** confidential to PMC-Sierra, Inc. PMC-Sierra distributes this software    **/
/** to its customers pursuant to the terms and conditions of the Software    **/
/** License Agreement contained in the text file software.lic that is        **/
/** distributed along with the software. This software can only be utilized  **/
/** if all terms and conditions of the Software License Agreement are        **/
/** accepted. If there are any questions, concerns, or if the                **/
/** Software License Agreement text file, software.lic, is missing please    **/
/** contact PMC-Sierra for assistance.                                       **/
/**--------------------------------------------------------------------------**/
/**                                                                          **/
/******************************************************************************/
/*******************************************************************************
**
**  MODULE      : HyPHY 20G SGMII Subsystem Configuration Code
**
**  FILE        : hyphy20g_mgmt_features.c
**
**  $Date: 2010-03-30 00:38:51 +0800 (星期二, 30 三月 2010) $
**
**  $Revision: 7221 $
**
**  DESCRIPTION :
**
**
**  NOTES       :
**
*******************************************************************************/

/** include files **/
#include "hyphy20g_api_wrapper.h"
#include "hyphy20g_mgmt_features.h"


/** external functions **/

/** external data **/

/** public data **/

/** private data **/

/******************************************************************************/
/* PRIVATE FUNCTION PROTOTYPES                                                */
/******************************************************************************/

/******************************************************************************/
/* PUBLIC FUNCTIONS                                                           */
/******************************************************************************/
/*******************************************************************************
**
**  hyPhy20gMgmtPortFeGePauseFrmCfg
**  ___________________________________________________________________________
**
**  DESCRIPTION:    This function configures PAUSE TIME and Pause Frame
**                  Interval in the TMAC block.
**
**                  The PAUSE TIME setting determines the 2 octets 'PAUSE_TIME'
**                  field in the outgoing MAC Pause Frames generated by TMAC.
**                  Refer to IEEE 802.3 for the MAC Pause Frame Format.
**                  If the far-end receiving station processes PAUSE flow
**                  control, it should inhibit data frame transmission for the
**                  length of time specificed by the received 'PAUSE_TIME'
**                  value.
**
**                  The Pause Frame Interval setting determines the time
**                  interval between 2 MAC PAUSE frames transmissions
**                  in the TMAC block.
**
**                  Both PAUSE TIME and Pause Frame Interval are measured
**                  in units of pause_quanta. Refer to IEEE 802.3 for
**                  pause_quanta details.
**
**                  Used for MAC Terminated (FE/GE, SGMII FE/GE) mode only.
**
**                  This function must be called after hyPhy20gMgmtPortInit.
**
**                  The default values provided in this description are
**                  relative to the state of the device after calling
**                  hyPhy20gMgmtPortInit.
**
**  INPUTS:         fileHndl  - device handle
**                  pauseTime - see function description
**                              Legal range 0x0001 to 0xFFFF
**                              Default setting 0xFFFF
**                  pauseInt  - see function description
**                              Legal range 0x0001 to 0xFFFF
**                              Default setting 0xEFFF
**
**  OUTPUTS:        None       - None
**
**  RETURNS:        HYPHY20G_ERR_INVALID_ARG
**                  HYPHY20G_ERR_DEV_ACCESS
**                  HYPHY20G_SUCCESS
**
*******************************************************************************/
INT4 hyPhy20gMgmtPortFeGePauseFrmCfg(struct file *fileHndl, UINT4 pauseTime,
                                     UINT4 pauseInt)
{
    INT4 result;
    UINT4 addr, msk;

    /* argument checking */
    if (pauseTime < 0x0001                  ||
        pauseTime > 0xFFFF                  ||
        pauseInt < 0x0001                   ||
        pauseInt > 0xFFFF) {
        return HYPHY20G_ERR_INVALID_ARG;
    }

    addr = HYPHY20G_SGMII_ENET_FEGE_TMAC_REG_PAUSE_FRM_TM_CFG;
    msk  = HYPHY20G_SGMII_ENET_FEGE_TMAC_BIT_PAUSE_FRM_TM_CFG_PAUSE_TIME_MSK;
    result = hyPhy20gRegFieldWrite(fileHndl, addr, msk, pauseTime);
    if(result) return result;

    addr = HYPHY20G_SGMII_ENET_FEGE_TMAC_REG_PAUSE_FRM_INTRVL_CFG;
    msk  = HYPHY20G_SGMII_ENET_FEGE_TMAC_BIT_PAUSE_FRM_INTRVL_CFG_PAUSE_IVAL_MSK;
    result = hyPhy20gRegFieldWrite(fileHndl, addr, msk, pauseInt);
    if(result) return result;

    return HYPHY20G_SUCCESS;

} /* hyPhy20gMgmtPortFeGePauseFrmCfg */


/*******************************************************************************
**
**  hyPhy20gMgmtPortFeGeSendFefi
**  ___________________________________________________________________________
**
**  DESCRIPTION:    This function can force sending FEFI.  The configuration is
**                  applied to the L1TPP block.
**
**                  Used for MAC Terminated FE mode only.
**
**                  When the receiver port is in LOS and the link is not
**                  configured for uni-directional operation (the bit 3 in
**                  register 0x4884000, unidirectional_mode is b'0), the L1TPP
**                  block sends FEF without software intervention.
**                  For rest of cases, this function may be called to
**                  enable or disable FEFI after a channel has been enabled.
**
**
**  INPUTS:         fileHndl  - device handle
**                  fefiEn    - 0 - normal frame transmission
**                              1 - send FEFI indication instead of normal frame
**
**  OUTPUTS:        None      - None
**
**  RETURNS:        HYPHY20G_ERR_INVALID_ARG
**                  HYPHY20G_ERR_DEV_ACCESS
**                  HYPHY20G_SUCCESS
**
*******************************************************************************/
INT4 hyPhy20gMgmtPortFeGeSendFefi(struct file *fileHndl, UINT4 fefiEn)
{
    INT4 result;
    UINT4 addr;

    /* argument checking */
    if (fefiEn > 1) {
        return HYPHY20G_ERR_INVALID_ARG;
    }

    addr = HYPHY20G_SGMII_ENET_FEGE_L1TPP_REG_CTL;
    result = sysHyPhy20gBitWrite(fileHndl, addr,
                HYPHY20G_SGMII_ENET_FEGE_L1TPP_BIT_CTL_FEF_GEN_EN_OFF, fefiEn);
    if(result) return result;

    return HYPHY20G_SUCCESS;
} /* hyPhy20gMgmtPortFeGeSendFefi */



/*******************************************************************************
**
**  hyPhy20gMgmtPortGeReAutoNeg
**  ___________________________________________________________________________
**
**  DESCRIPTION:    This function will restart Auto-Negotiation state machine
**                  and will make the device begin the Auto-Negotiation
**                  process again.
**
**                  It is user's responsibility to ensure this function is only
**                  used in GE MAC Terminated mode and auto-negotiation is
**                  enabled.
**
**                  Calling this function will interrupt the data flow in case
**                  of the data flow is previously enabled.
**
**  INPUTS:         fileHndl  - device handle
**
**  OUTPUTS:        None      - None
**
**  RETURNS:        HYPHY20G_ERR_DEV_ACCESS
**                  HYPHY20G_ERR_INVALID_PRECONFIG
**                  HYPHY20G_ERR_INVALID_ARG
**                  HYPHY20G_ERR_POLL_TIMEOUT
**                  HYPHY20G_SUCCESS
**
*******************************************************************************/
INT4 hyPhy20gMgmtPortGeReAutoNeg(struct file *fileHndl)
{
    INT4 result;
    UINT4 addr;
    UINT4 anEnblOff;
    UINT4 anEnblVal;
    UINT4 anRstOff;
    UINT4 anRstMsk;

    addr = HYPHY20G_SGMII_ENET_FEGE_L1RPP_REG_MII_CTL;
    anEnblOff = HYPHY20G_SGMII_ENET_FEGE_L1RPP_BIT_MII_CTL_AN_ENABLE_OFF;
    anRstOff = HYPHY20G_SGMII_ENET_FEGE_L1RPP_BIT_MII_CTL_AN_RESTART_OFF;
    anRstMsk = HYPHY20G_SGMII_ENET_FEGE_L1RPP_BIT_MII_CTL_AN_RESTART_MSK;

    /* read out AN_ENABLE value */
    result = sysHyPhy20gBitRead(fileHndl, addr, anEnblOff, &anEnblVal);
    if(result) return result;

    /* ensure AN_ENABLE is b'1 at first */
    if (anEnblVal == 0) {
        return HYPHY20G_ERR_INVALID_PRECONFIG;
    }

    /* enable AN_RESTART bit to restart auto-negotiation */
    result = sysHyPhy20gBitWrite(fileHndl, addr, anRstOff, 1);
    if(result) return result;

    /* Poll register bit to make sure bit is cleared */
    result = sysHyPhy20gPollBit(fileHndl, addr, anRstMsk, 0, 1);
    if (result) return result;

    return HYPHY20G_SUCCESS;
} /* hyPhy20gMgmtPortGeReAutoNeg */


/*******************************************************************************
**
**  hyPhy20gMgmtPortGeAnBasePageCfg
**  ___________________________________________________________________________
**
**  DESCRIPTION:    This function configures remote and pause capability
**                  encoding in the auto-negotiation ADVERTISEMENT
**                  register (base page). Changes of base page register will
**                  be exchanged during renegotiation.
**
**                  It is user's responsibility to ensure this function is only
**                  used in GE MAC Terminated mode and auto-negotiation is
**                  enabled.
**
**                  Refer to IEEE 802.3 2000 clause 28 for details of the
**                  base page register fields.
**
**                  Refer to IEEE 802.3 2000 Annex 28B for details of remote
**                  fault and pause capability encoding.
**
**                  It is the user the responsibility to resolute pause
**                  capability according to IEEE 802.3 2000 Table 28B-3.
**
**                  This function can be used in two scenarios:
**                  1) call this function to initialize local device
**                  pause capability after calling hyPhy20gLsciInit
**                  but piror to call hyPhy20gLsciFeGeModeCfg;
**                  'reNegFlg' parameter must be b'0 in this case.
**
**                  2) dynamically call this function to change Remote fault
**                  and pause capability setting after hyPhy20gLsciFeGeModeCfg
**                  called;
**                  User may optionally restart the auto-negotiation by
**                  setting 'reNegFlg' parameter to b'1.
**
**  INPUTS:         fileHndl  - device handle
**                  remoteFlt - Remote fault
**                              0 - No error, link OK
**                              1 - Link Failure
**                              2 - Offline
**                              3 - Auto-Negotiation_Error
**                              default value is b'00;
**                  pauseVal  - pause capability of local device
**                              0 - No pause
**                              1 - Symmetric PAUSE
**                              2 - Asymmetric PAUSE towardlink partner
**                              3 - Both Symmetric PAUSE and Asymmetric PAUSE
**                                  toward local device
**                              device default value is b'00;
**                              default value after hyPhy20gLsciInit function
**                              call is b'11;
**                  reNegFlg  - whether restart the auto-negotiation
**                              0 - don't renegotiation
**                              1 - renegotiation
**
**  OUTPUTS:        None       - None
**
**  RETURNS:        HYPHY20G_ERR_INVALID_ARG
**                  HYPHY20G_ERR_DEV_ACCESS
**                  HYPHY20G_ERR_INVALID_PRECONFIG
**                  HYPHY20G_ERR_POLL_TIMEOUT
**                  HYPHY20G_SUCCESS
**
*******************************************************************************/
INT4 hyPhy20gMgmtPortGeAnBasePageCfg(struct file *fileHndl, UINT4 remoteFlt,
                                     UINT4 pauseVal, UINT4 reNegFlg)
{
    INT4 result;
    UINT4 basePgAddr;
    UINT4 remoteFltMsk;
    UINT4 pauseMsk;
    UINT4 regData;

    /* argument checking */
    if (remoteFlt > 3   ||
        pauseVal > 3    ||
        reNegFlg > 1) {
        return HYPHY20G_ERR_INVALID_ARG;
    }

    basePgAddr   = HYPHY20G_SGMII_ENET_FEGE_L1RPP_REG_MII_AUTO_NEG_AD;
    remoteFltMsk = HYPHY20G_SGMII_ENET_FEGE_L1RPP_BIT_MII_AUTO_NEG_AD_RF_MSK;
    pauseMsk     = HYPHY20G_SGMII_ENET_FEGE_L1RPP_BIT_MII_AUTO_NEG_AD_PS_MSK;

    /* configure  MII AUTO-NEGOTIATION ADVERTISEMENT register (base page) */
    result = sysHyPhy20gRead(fileHndl, basePgAddr, &regData);
    if(result) return result;

    result = hyPhy20gVarFieldWrite (&regData, remoteFltMsk, remoteFlt);
    if(result) return result;

    result = hyPhy20gVarFieldWrite (&regData, pauseMsk, pauseVal);
    if(result) return result;

    result = sysHyPhy20gWrite(fileHndl, basePgAddr, regData);
    if(result) return result;

    if (reNegFlg) {
        result = hyPhy20gMgmtPortGeReAutoNeg(fileHndl);
        if(result) return result;
    }

    return HYPHY20G_SUCCESS;

} /* hyPhy20gMgmtPortGeAnBasePageCfg */


/******************************************************************************/
/* PRIVATE FUNCTIONS                                                          */
/******************************************************************************/


/* end of file */
